# cocos2d
list(APPEND duole_cocos2d_libs -Wl,--whole-archive cpp_android_spec -Wl,--no-whole-archive)
list(APPEND duole_cocos2d_libs -Wl,--whole-archive lua_android_spec -Wl,--no-whole-archive)
list(APPEND duole_cocos2d_libs "cocos2d")
list(APPEND duole_cocos2d_libs "luacocos2d")

# prebuilt
list(APPEND duole_cocos2d_libs "ext_chipmunk")
list(APPEND duole_cocos2d_libs "ext_box2d")
list(APPEND duole_cocos2d_libs "ext_freetype")
list(APPEND duole_cocos2d_libs "ext_jpeg")
list(APPEND duole_cocos2d_libs "ext_uv")
list(APPEND duole_cocos2d_libs "ext_webp")
list(APPEND duole_cocos2d_libs "ext_websockets")
list(APPEND duole_cocos2d_libs "ext_ssl")
list(APPEND duole_cocos2d_libs "ext_crypto")
list(APPEND duole_cocos2d_libs "ext_tiff")
list(APPEND duole_cocos2d_libs "ext_linearmath")
list(APPEND duole_cocos2d_libs "ext_bulletcollision")
list(APPEND duole_cocos2d_libs "ext_bulletdynamics")
list(APPEND duole_cocos2d_libs "ext_bulletmultithreaded")
list(APPEND duole_cocos2d_libs "ext_minicl")
list(APPEND duole_cocos2d_libs "ext_curl")
list(APPEND duole_cocos2d_libs "ext_png")
list(APPEND duole_cocos2d_libs "ext_zlib")

# src
list(APPEND duole_cocos2d_libs "ext_cjson")
list(APPEND duole_cocos2d_libs "ext_clipper")
list(APPEND duole_cocos2d_libs "ext_convertUTF")
list(APPEND duole_cocos2d_libs "ext_edtaa3func")
list(APPEND duole_cocos2d_libs "ext_lua_extensions")
list(APPEND duole_cocos2d_libs "ext_lua515")
list(APPEND duole_cocos2d_libs "ext_luasocket")
list(APPEND duole_cocos2d_libs "ext_md5")
list(APPEND duole_cocos2d_libs "ext_poly2tri")
list(APPEND duole_cocos2d_libs "ext_pvmp3dec")
list(APPEND duole_cocos2d_libs "ext_cpufeatures")
list(APPEND duole_cocos2d_libs "ext_recast")
list(APPEND duole_cocos2d_libs "ext_tinyxml2")
list(APPEND duole_cocos2d_libs "ext_tolua")
list(APPEND duole_cocos2d_libs "ext_tremolo")
list(APPEND duole_cocos2d_libs "ext_unzip")
list(APPEND duole_cocos2d_libs "ext_xxhash")
list(APPEND duole_cocos2d_libs "ext_xxtea")